version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root2022
      MYSQL_USER: root
      MYSQL_PASSWORD: root2022
      MYSQL_DATABASE: testdemo
    volumes:
      - ./maria-data:/data/db
    ports:
      - "3306:3306"
  ## Eureka Server
  discovery-server:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "9090:9090"
    depends_on:
      - discovery-server
      - db
  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    container_name: appointment-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server