version: '3.7'
services:
  ##Mongo Database
  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db   # Define the volume here

  ##MariaDb
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root2022

  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:9090"
  ## Discovery Server
  discovery-server:
    build: ./eureka-service
    container_name: discovery-server
    ports:
      - "8761:8761"

  ##Appointment Service
  appointment-service:
    depends_on:
      - discovery-server
      - mongo
    build: ./appointment-service
    container_name: appointment-service
    ports:
      - "8082:8082"

  ##Patient Service
  patient-service:
    depends_on:
      - discovery-server
      - db
    build: ./patient-service
    container_name: patient-server
    ports:
      - "8081:8081"

