server:
  port: 9090
spring:
  application:
    name: patient-service
  datasource:
    username: root
    password: root2022
    url: jdbc:mariadb://localhost:3306/testdemo
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
