server:
  port: 8082
spring:
  application:
    name: appointment-service
  data:
    mongodb:
      database: appointment
      host: mongo
      port: 27017
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
