server:
  port: 8082
spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mariadb://localhost:3306/testdemo
    username: root
    password: root2022
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
